name: Build and test

on: [push, pull_request]

env:
  buildDir: ${{ github.workspace }}/build/

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            triplet: x64-linux
          - os: windows-2019
            triplet: x64-windows
          - os: macos-11
            triplet: x64-osx

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'recursive'

      - uses: lukka/get-cmake@latest

      - name: Build
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          buildDirectory: ${{ env.buildDir }}
          buildWithCMake: true
          cmakeAppendedArgs: -DPV_BUILD_TESTS=ON -DPV_BUILD_BENCHMARKS=ON -DPV_WARNINGS_AS_ERRORS=ON -DCMAKE_BUILD_TYPE=Debug

      - name: Test 1
        run: cd "${{ env.buildDir }}"; ctest --output-on-failure --timeout 10
        shell: bash

      - name: Build (no shared storage)
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          buildDirectory: ${{ env.buildDir }}
          buildWithCMake: true
          cmakeAppendedArgs: -DPV_BUILD_TESTS=ON -DPV_BUILD_BENCHMARKS=ON -DPV_WARNINGS_AS_ERRORS=ON -DPV_EXPLOIT_SHARED_STORAGE=OFF -DCMAKE_BUILD_TYPE=Debug

      - name: Test 2
        run: cd "${{ env.buildDir }}"; ctest --output-on-failure --timeout 10
        shell: bash
