name: PR-Checks

on: [pull_request]

env:
  buildDir: ${{ github.workspace }}/build/

jobs:
  pr-checks:
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2
      with:
          submodules: 'recursive'

    - name: Check line endings
      uses: erclu/check-crlf@v1
  
    - uses: lukka/get-cmake@latest

    - name: Configure
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        buildDirectory: ${{ env.buildDir }}
        buildWithCMake: false
        cmakeAppendedArgs: -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Link compile-command DB
      run: ln -s "${{ env.buildDir }}/compile_commands.json" .
      shell: bash

    - name: Check code formatting
      uses: jidicula/clang-format-action@v3.3.0
      with:
          clang-format-version: '10'
          check-path: '.'
          exclude-regex: '(build/*)'
